# This is a basic workflow that is manually triggered

name: manual_tests_CPU

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Make the default shell a login shell, so that conda is initialised properly
    defaults:
      run:
        shell: bash -el {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        python-version: "3.10"
    - name: pip install
      run:  |
        pip install numpy==1.24.2 scipy h5py 'pyvista[all,trame]' tqdm
        pip install matplotlib pytest
    - name: Print versions
      run: conda list
    - name: Checkout wakis
      uses: actions/checkout@v4
      with:
        path: wakis
    - name: Run pytest
      run:  |
        cd wakis
        python -m pytest --color=yes -v -s tests -m "not interactive"
